### ISSUE TITLE
[meetup] Iterators and Generators

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/.maintainers#43]
## Tasks - Do these in Order
- [x] Create Outline - https://github.com/BlackPythonDevs/.maintainers/discussions/44
- [x] Create Event Graphic - (@VeldaKiara)
- [x] Create Event in Discord - (@VeldaKiara)
- [x] Add to website - https://github.com/BlackPythonDevs/blackpythondevs.com/issues/create
- [x] Promote in our discord - @GabyM (pending Username)
- [x] Promote the event on social media - (everyone!)

## Record and Publish Event if Permitted
- [x] Stream to YouTube and LinkedIn? (@kjaymiller)
- [x] Promote on social media (everyone)
- [x] Send follow up to let folks know to join the discord to participate in events or suggest topics
